apiVersion: datadog.upbound.io/v1alpha1
kind: MonitorJSON
metadata:
  annotations:
    meta.upbound.io/example-id: datadog/v1alpha1/monitorjson
  labels:
    testing.upbound.io/example-name: monitor_json
  name: monitor-json
spec:
  forProvider:
    monitor: "{\n    \"name\": \"Example monitor - service check\",\n    \"type\":
      \"service check\",\n    \"query\": \"\\\"ntp.in_sync\\\".by(\\\"*\\\").last(2).count_by_status()\",\n
      \   \"message\": \"Change the message triggers if any host's clock goes out
      of sync with the time given by NTP. The offset threshold is configured in the
      Agent's 'ntp.yaml' file.\\n\\nSee [Troubleshooting NTP Offset issues](https://docs.datadoghq.com/agent/troubleshooting/ntp
      for more details on cause and resolution.\",\n    \"tags\": [],\n    \"multi\":
      true,\n\t\"restricted_roles\": null,\n    \"options\": {\n        \"include_tags\":
      true,\n        \"new_host_delay\": 150,\n        \"notify_audit\": false,\n
      \       \"notify_no_data\": false,\n        \"thresholds\": {\n            \"warning\":
      1,\n            \"ok\": 1,\n            \"critical\": 1\n        }\n    },\n
      \   \"priority\": null,\n    \"classification\": \"custom\"\n}\n"
