apiVersion: datadog.upbound.io/v1alpha1
kind: TeamLink
metadata:
  annotations:
    meta.upbound.io/example-id: datadog/v1alpha1/teamlink
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    label: Link label
    position: 0
    teamId: ${datadog_team.foo.id}
    url: https://example.com

---

apiVersion: datadog.upbound.io/v1alpha1
kind: Team
metadata:
  annotations:
    meta.upbound.io/example-id: datadog/v1alpha1/teamlink
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    description: Example team
    handle: example-team-updated
    name: Example Team-updated
